require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe Providers::BankDetailsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Providers::BankDetail. As you add validations to Providers::BankDetail, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Providers::BankDetailsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all providers_bank_details as @providers_bank_details" do
      bank_detail = Providers::BankDetail.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:providers_bank_details)).to eq([bank_detail])
    end
  end

  describe "GET #show" do
    it "assigns the requested providers_bank_detail as @providers_bank_detail" do
      bank_detail = Providers::BankDetail.create! valid_attributes
      get :show, params: {id: bank_detail.to_param}, session: valid_session
      expect(assigns(:providers_bank_detail)).to eq(bank_detail)
    end
  end

  describe "GET #new" do
    it "assigns a new providers_bank_detail as @providers_bank_detail" do
      get :new, params: {}, session: valid_session
      expect(assigns(:providers_bank_detail)).to be_a_new(Providers::BankDetail)
    end
  end

  describe "GET #edit" do
    it "assigns the requested providers_bank_detail as @providers_bank_detail" do
      bank_detail = Providers::BankDetail.create! valid_attributes
      get :edit, params: {id: bank_detail.to_param}, session: valid_session
      expect(assigns(:providers_bank_detail)).to eq(bank_detail)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Providers::BankDetail" do
        expect {
          post :create, params: {providers_bank_detail: valid_attributes}, session: valid_session
        }.to change(Providers::BankDetail, :count).by(1)
      end

      it "assigns a newly created providers_bank_detail as @providers_bank_detail" do
        post :create, params: {providers_bank_detail: valid_attributes}, session: valid_session
        expect(assigns(:providers_bank_detail)).to be_a(Providers::BankDetail)
        expect(assigns(:providers_bank_detail)).to be_persisted
      end

      it "redirects to the created providers_bank_detail" do
        post :create, params: {providers_bank_detail: valid_attributes}, session: valid_session
        expect(response).to redirect_to(Providers::BankDetail.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved providers_bank_detail as @providers_bank_detail" do
        post :create, params: {providers_bank_detail: invalid_attributes}, session: valid_session
        expect(assigns(:providers_bank_detail)).to be_a_new(Providers::BankDetail)
      end

      it "re-renders the 'new' template" do
        post :create, params: {providers_bank_detail: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested providers_bank_detail" do
        bank_detail = Providers::BankDetail.create! valid_attributes
        put :update, params: {id: bank_detail.to_param, providers_bank_detail: new_attributes}, session: valid_session
        bank_detail.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested providers_bank_detail as @providers_bank_detail" do
        bank_detail = Providers::BankDetail.create! valid_attributes
        put :update, params: {id: bank_detail.to_param, providers_bank_detail: valid_attributes}, session: valid_session
        expect(assigns(:providers_bank_detail)).to eq(bank_detail)
      end

      it "redirects to the providers_bank_detail" do
        bank_detail = Providers::BankDetail.create! valid_attributes
        put :update, params: {id: bank_detail.to_param, providers_bank_detail: valid_attributes}, session: valid_session
        expect(response).to redirect_to(bank_detail)
      end
    end

    context "with invalid params" do
      it "assigns the providers_bank_detail as @providers_bank_detail" do
        bank_detail = Providers::BankDetail.create! valid_attributes
        put :update, params: {id: bank_detail.to_param, providers_bank_detail: invalid_attributes}, session: valid_session
        expect(assigns(:providers_bank_detail)).to eq(bank_detail)
      end

      it "re-renders the 'edit' template" do
        bank_detail = Providers::BankDetail.create! valid_attributes
        put :update, params: {id: bank_detail.to_param, providers_bank_detail: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested providers_bank_detail" do
      bank_detail = Providers::BankDetail.create! valid_attributes
      expect {
        delete :destroy, params: {id: bank_detail.to_param}, session: valid_session
      }.to change(Providers::BankDetail, :count).by(-1)
    end

    it "redirects to the providers_bank_details list" do
      bank_detail = Providers::BankDetail.create! valid_attributes
      delete :destroy, params: {id: bank_detail.to_param}, session: valid_session
      expect(response).to redirect_to(providers_bank_details_url)
    end
  end

end
